# Generated by Django 5.2.3 on 2025-07-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_photo_userconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='is_confirned',
            new_name='is_confirmed',
        ),
    ]
