databases:
  - name: instagram-db
    databaseName: instagram_db
    user: instagram_user
    plan: free

services:
  - type: web
    name: instagram-clone
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: instagram-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,http://localhost:8000,http://127.0.0.1:8000"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@instagramclone.com"
      - key: account_sid
        sync: false
      - key: auth_token
        sync: false
